version: '3.8'

services:
    ### 🔹 MongoDB Database ###
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        volumes:
            - mongodb_data:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "root"

    ### 🔹 Laravel Backend (API) ###
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mini-ticket-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mongodb
        ports:
            - "8000:8000"
        environment:
            APP_ENV: local
            APP_KEY: base64:randomkey
            DB_CONNECTION: mongodb
            DB_HOST: mongodb
            DB_PORT: 27017
            DB_DATABASE: ticketing
            DB_USERNAME: admin
            DB_PASSWORD: root
            MONGO_URI: mongodb://admin:root@mongodb:27017/ticketing
        command: php artisan serve --host=0.0.0.0 --port=8000

    ### 🔹 Vue.js Frontend ###
    frontend:
        build:
            context: .
            dockerfile: frontendDockerfile
        container_name: mini-ticketing-frontend
        restart: unless-stopped
        ports:
            - "5173:5173"
        volumes:
            - .:/app
        depends_on:
            - backend
        command: npm run dev -- --host 0.0.0.0

volumes:
    mongodb_data:

